language: php
php:
  - '7.1'
directories:
  - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
after_script:
  - make test-cs